# Comparision Operation

In [1]:
import numpy as np
a = np.arange(10)
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [2]:
import numpy as np
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

# Dot

In [ ]:
import numpy as np
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

# Reshape

In [3]:
import numpy as np
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])