# Pyinstaller
- pyinstaller --onefile --noconsole <파일명>.py

# 2중 List를 Flatten하게 만들기

In [56]:
sum([[1,2],[3,4]], [])

[1, 2, 3, 4]

In [57]:
[y for x in [[1,2],[3,4]] for y in x]

[1, 2, 3, 4]

- 속도 비교 #1 (sum이 더 빠르다.)

In [58]:
import timeit
print(timeit.timeit('sum([[1,2],[3,4]], [])', number=10000))
print(timeit.timeit('[y for x in [[1,2],[3,4]] for y in x]', number=10000))

0.010635299999876224
0.020347800000081406


- 속도 비교 #2 (역시 sum이 더 빠르다.)

In [60]:
%timeit sum([[1,2],[3,4]], [])

1.04 µs ± 276 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [61]:
%timeit [y for x in [[1,2],[3,4]] for y in x]

1.24 µs ± 181 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 한 줄에 변수 2개를 int로 받기

In [62]:
a, b = map(int, input().split(" "))

1 2


In [63]:
print(a, b)

1 2


# 문자열 반복
- 백준알고리즘2675번: https://www.acmicpc.net/problem/2675
- ex) input에 2 abc 넣어보기

In [68]:
R, S = input().split()
text = ""
for j in S:
    text += j*int(R)
print(text)

2 abc
aabbcc


# Threading

In [1]:
import threading
import time

def print_apple():
    print("사과가 먹고 싶어요.")
    
    threading.Timer(2.5, print_apple).start()

In [3]:
print_apple()

사과가 먹고 싶어요.
사과가 먹고 싶어요.
사과가 먹고 싶어요.
사과가 먹고 싶어요.
사과가 먹고 싶어요.


# Requests
- GET은 requests.get()이고 params=params
- POST는 requests.post()이고 data=data

In [22]:
import requests

URL = "http://www.tistory.com"
headers = {'Content-Type': 'application/json; charset=utf-8'}
params = {'param1': 'value1', 'param2': 'value'}
cookies = {'session_id': 'sorryidontcare'} 
req = requests.get(URL, headers=headers, params=params, cookies=cookies)
res = req.content

In [23]:
req.url

'https://www.tistory.com/?param1=value1&param2=value'

In [24]:
req

<Response [200]>

In [25]:
req.status_code

200

- header가 json일 경우

In [41]:
import requests

URL = "http://httpbin.org/post"
headers = {
    'User-Agent': ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 '
                   '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'),
    'Referer': 'http://httpbin.org',
}
params = {'k1': 'v1', 'k2': 'v2'}
req = requests.post(URL, headers=headers,params=params)

- parameter가 json일 경우

In [20]:
import requests
import json

URL = "http://www.tistory.com"
params = {'outer': {'inner': 'value'}}
req = requests.get(URL, params=json.dumps(params))

- response가 json일 경우

In [26]:
import requests
import json

params = (('k1', 'v1'), ('k1', 'v3'), ('k2', 'v2'))
req = requests.get('http://httpbin.org/get', params=params)
res = req.text

In [34]:
req.json()

{'args': {'k1': ['v1', 'v3'], 'k2': 'v2'},
 'headers': {'Accept': '*/*',
  'Accept-Encoding': 'gzip, deflate',
  'Host': 'httpbin.org',
  'User-Agent': 'python-requests/2.21.0',
  'X-Amzn-Trace-Id': 'Root=1-5f24ddb1-81dff99e059d37865669fb1d'},
 'origin': '125.129.7.7',
 'url': 'http://httpbin.org/get?k1=v1&k1=v3&k2=v2'}

In [38]:
print(res)

{
  "args": {
    "k1": [
      "v1", 
      "v3"
    ], 
    "k2": "v2"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.21.0", 
    "X-Amzn-Trace-Id": "Root=1-5f24ddb1-81dff99e059d37865669fb1d"
  }, 
  "origin": "125.129.7.7", 
  "url": "http://httpbin.org/get?k1=v1&k1=v3&k2=v2"
}



In [39]:
print(json.loads(res))

{'args': {'k1': ['v1', 'v3'], 'k2': 'v2'}, 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.21.0', 'X-Amzn-Trace-Id': 'Root=1-5f24ddb1-81dff99e059d37865669fb1d'}, 'origin': '125.129.7.7', 'url': 'http://httpbin.org/get?k1=v1&k1=v3&k2=v2'}


In [40]:
print(json.loads(res)["args"])

{'k1': ['v1', 'v3'], 'k2': 'v2'}


# Numpy
- Comparision Operation

In [43]:
import numpy as np
a = np.arange(10)
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [44]:
import numpy as np
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

- Reshape

In [46]:
import numpy as np
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

- Dot

In [45]:
import numpy as np
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

# Papago Translate
- cis : https://twitter.com/cissan_9984

In [78]:
CLIENT_ID = <클라이언트 아이디>
CLIENT_SECRET = <클라이언트 시크릿>
TEXT = "俺のツイッターのアカウントこれだけです"

import requests

url = "https://openapi.naver.com/v1/papago/n2mt"
headers = {
    "X-Naver-Client-Id": CLIENT_ID,
    "X-Naver-Client-Secret": CLIENT_SECRET
}
data = {"source": "ja", "target":"ko", "text":TEXT}
res = requests.post(url, headers=headers, data=data)
print(res.text)

{"message":{"@type":"response","@service":"naverservice.nmt.proxy","@version":"1.0.0","result":{"srcLangType":"ja","tarLangType":"ko","translatedText":"제 트위터 계정 이것뿐이에요","engineType":"N2MT","pivot":null}}}
